language: node_js
node_js:
  - '0.12'
  - '4'
  - 'stable'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bootstrap-kickstart' ]; then cd .. && eval "mv $currentfolder generator-bootstrap-kickstart" && cd generator-bootstrap-kickstart; fi
script:
  npm run coveralls
